name: Gh-Pages

on: 
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: windows
    
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: bluefireteam/flutter-gh-pages@v7
